#!/usr/bin/env python
# encoding: utf-8
#
# Copyright (c) 2010 Doug Hellmann.  All rights reserved.
#
"""Client half of echo example
"""
#end_pymotw_header

import os
import socket
import sys

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Connect the socket to the port where the server is listening
os.popen('iptables -I INPUT 1 -p tcp --dport 10000 -j ACCEPT')
server_address = ('192.168.122.1', 10000)
print >>sys.stderr, 'connecting to %s port %s' % server_address
sock.connect(server_address)

try:
    # Send data
    hostname=os.popen('hostname').read()
    ip=os.popen("hostname -I | awk '{print $1}'").read()
    message = '%s %s' % (hostname, ip)
    sock.sendall(message)

finally:
    print >>sys.stderr, 'closing socket'
    sock.close()
