#!/bin/bash

echo 1 > /proc/sys/net/ipv4/ip_forward
sed -i "s,#net.ipv4.ip_forward = 1,net.ipv4.ip_forward = 1,g" /etc/sysctl.conf
mkdir -p /cloud/_base
mkdir -p /cloud/keys/
cp -rf ./centos* /cloud/_base
cp -rf ./controller_node /cloud/_base/
cp -rf ./vsm-allinone /cloud/
cp -rf virbr* /cloud/_base/

for n in 1 2 3 4; do
    sed -i "s,%UUID$n%,`uuidgen`,g" /cloud/_base/virbr${n}.xml
    virsh net-define /cloud/_base/virbr${n}.xml
    virsh net-start virbr$n
    virsh net-autostart virbr$n
done

cp -rf iptables /root/
for n in `hostname -I`; do
    if [[ `echo $n | grep 239 | wc -l` -gt 0 ]]; then
        sed -i "s,10.249.66.104,$n,g" /root/iptables
    fi
done
iptables-restore < /root/iptables

cp -rf host_name_server /root/
cp -rf client /cloud/
pgrep host_name_server | xargs -i kill -9 {}
python /root/host_name_server >/dev/null 2>&1 &

# Prepare keys
mkdir -p /cloud/keys/
[[ -e ~/.ssh ]] && cp -rf ~/.ssh/*.pub /cloud/keys/
find /home -name "*.pub" | xargs -i cp -rf {} /cloud/keys/
